### ISSUE TITLE
kind of 404 downloading statistics

### ISSUE THREAD

**Issue by federicomorando** [nexacenter/public-contracts#17] opened 2015-06-16 10:22 UTC
From http://public-contracts.nexacenter.org/?05599740965
clicking on "statistiche" http://public-contracts.nexacenter.org/download/05599740965/stats.json
you get
```
Cannot GET /download/05599740965/stats.json
```

**Comment by alemela** [comment] 2015-06-16 10:25
Duplicate of #16

**Closed by alemela** 2015-06-16 10:25 UTC
Labels: duplicate
